### ISSUE TITLE
Ctrl + Cでプロセスが終了しない

### ISSUE THREAD

**Issue by csenet** [ueckoken/plarail2023#242]
## 不具合の内容

現状「state-manager」を実行した状態で、Ctrl + Cでプロセスを終了しようとしても落ちない。

### 現象・ログ

Ctrl + Cを押すと、
```
2023-11-21T16:22:53.367548+09:00 INFO signal received 
```
と表示された後、一向に終了しない。

### 再現手順

main.goを実行して、Ctrl + Cで終了を試みる。

### 期待動作

Ctrl + Cで正常に終了する。

**Comment by Azuki-bar** [comment]
心当たりあります
