### ISSUE TITLE
ドキュメントを作る

### ISSUE THREAD

**Issue by kienn-HCl** [ueckoken/plarail2023#3]
初めて参加する部員がプラレール企画について把握しやすくするために、きちんとドキュメントを整備したい。

**Comment by kienn-HCl** [comment]
gh-pagesブランチにmdbookでビルドしたのをデプロイするようにした。
このリポジトリのsetting私いじれないみたいだからGithub Pages の設定やってくれ @csenet

**Comment by csenet** [comment]
@kienn-HCl 
設定しておいた。
https://ueckoken.github.io/plarail2023
一応、Adminに昇格させておいたので自由にSettings触れるようになったはず。

**Comment by csenet** [comment]
ある程度ドキュメントは完成したのでClose
